pages/k8s/quickstart.md

This still has a few things to tidy up in terms of formatting and sorting out the images, but the words are readyish

Add first draft of quick start

---

pages/k8s/quickstart.md

@tvansteenburgh I added this to the end of the quickstart because it isn't really long enough to warrant a page, but happy to move it if you disagree. I think it rounds off this section on a nice positive 'something achieved' note.

Add log in to Dashboard 

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/monitoring.md

Add monitoring page

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/decommissioning.md

Add decommissioning page

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/validation.md

Add Validation/e2e

---

pages/release-notes/00000000-0.00
pages/release-notes/20180817-1.12

As discussed in standup, we'll use this branch to iterate on release notes for 1.12 prior to merging to master.

[WIP] Release notes for 1.12

---

_data/sidebars/k8smain-sidebar.yml
_includes/head.html
_includes/sidenav.html
_includes/vanilla-overrides.html

This makes them like the other docs sites

Fix and simplify nav styles

---

pages/k8s/install-local.md

Add localhost install

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/troubleshooting.md

Add troubleshooting page

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/storage.md

Add main Storage page Ceph/NFS

---

_data/topnav.yml
_includes/head.html
_includes/header.html
_includes/topnav.html

Add proper links and temporarily remove search box (needs to be configured on appliance?)

Fix top navigation menu

---

pages/k8s/install-local.md

Fixed broken link

---

pages/release-notes/20181115-1.13

I wonder if we should link the docs

Adding keystone information

---

pages/release-notes/20181115-1.13.md

Clean up fixes in release notes 1.13

---

assets/keystone.yaml
assets/policy.yaml
pages/k8s/ldap.md
pages/k8s/troubleshooting.md

Sorry @hyperbolic2346 it was easier to create a new PR
I'll mail you the diff if you like!

Add LDAP page

---

pages/k8s/backups.md

This syncs the backups file in the repo with the currently published docs on u.c

Sync backups with u.c

---

pages/k8s/backups.md
pages/k8s/decommissioning.md

This syncs the decommissioning page with docs published on u.c

Sync decommissioning

---

pages/k8s/upgrade-notes.md

Add warning to  upgrade-notes.md

---

pages/k8s/using-vault.md

Follow up from https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/714#issuecomment-467401802

Fixed missing relationship between load-balancer and vault

---

pages/k8s/quickstart.md

Dashboard clarification

---

pages/k8s/install-manual.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/112

Backport #112 to current

---

_data/sidebars/k8smain-sidebar.yml
assets/gcp-overlay.yaml
pages/k8s/aws-integration.md
pages/k8s/gcp-integration.md
pages/k8s/install-manual.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/108

Backport #108 to current

---

netlify.toml

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/117

Backport #117 to current

---

pages/k8s/release-notes.md

Some details for your bits, @Cynerva and @hyperbolic2346

Draft release notes

---

pages/k8s/high-availability.md

ummm, I don't know how I wrote that word soup

---

pages/k8s/hacluster.md

The original writing was vague about the 3 units. Adding details to clarify it.
Also reworded the validation part with @tvansteenburgh.

Cleanup quorum details

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/tigera-secure-ee.md

Pulled from a wiki page here: https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Using-Tigera-Secure-EE-with-CDK

Add doc page for Tigera Secure EE

---

pages/k8s/metallb.md

No need to state what we can't do.

Remove mention of CaaS charms

---

pages/k8s/metallb.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/133

Backport #133 to current

---

pages/k8s/monitoring.md

- s/Canonical/Charmed where appropriate
- use bionic series
- use prometheus2 charm with necessary constraints
- remove nrpe-external-master (same functionality has been merged into nrpe)
- remove topbeat (no bionic version available, and the xenial subordinate will not work)

refresh monitoring section

---

pages/k8s/monitoring.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/135

Backport #135 to current

---

pages/k8s/ldap.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/139

Backport #139 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

Notes and links for bugfix release

---

index.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/150

Backport #150 to current

---

pages/k8s/troubleshooting.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/155

Backport #155 to current

---

pages/k8s/aws-integration.md

link to aws console was malformed

fix console link

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/auth.md

it was easier to resubmit than rescue a branch from a fork of a different repo
lines 120-129 are the new bits

Rework of rbac page

---

_data/topnav.yml
pages/k8s/aws-integration.md
pages/k8s/certs-and-trust.md
pages/k8s/encryption-at-rest.md
pages/k8s/gcp-integration.md
pages/k8s/gpu-workers.md
pages/k8s/hacluster.md
pages/k8s/install-manual.md
pages/k8s/operations.md
pages/k8s/using-vault.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/158

Backport #158 to current

---

_data/sidebars/k8smain-sidebar.yml

docker nav

---

_data/sidebars/k8smain-sidebar.yml

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/164

Backport #164 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

Will fill in bundle revision once it's known.

Added bugfix release notes

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/auth.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/159

Backport #159 to current

---

pages/k8s/release-notes.md

as suggested https://github.com/charmed-kubernetes/kubernetes-docs/pull/173. I am adding docs for this change in the release notes.

Adding load balancer IP information

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

We're gearing up to do a hotfix release soon. Here's a release note. We'll need to update this with the correct date and bundle revision before we can merge it.

Hotfix release notes ~2019-05-10

---

pages/k8s/scaling.md

this partially addresses the issues raised in #183

Add note regarding autoscale

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/cni-calico.md

This should probably be merged to the branch in https://github.com/charmed-kubernetes/kubernetes-docs/pull/175 instead of master. But I gotta open this PR for that sweet, sweet preview page.
~Still WIP, I'll let you know when I'm done.~ I'm done.

[draft] Calico BGP

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

~~Hold for stable release revisions.~~
Edit: ready for review; hotfix charms/bundles were published to stable this morning.

Hotfix release notes ~2019-06-18

---

pages/k8s/release-notes.md

Based off https://github.com/charmed-kubernetes/kubernetes-docs/pull/167/files
Probably needs some butter.

Containerd release notes

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/container-runtime.md
pages/k8s/upgrade-notes.md
pages/k8s/upgrading.md

containerd

---

pages/k8s/using-vault.md

This adds more detail to the HA mode instructions, confirmed via manual testing.

Expand instructions for HA mode

---

pages/k8s/release-notes.md

Heyo. I just fixed an issue and wanted to be proactive about making a release note for it. Feels like it isn't done until there's a release note ready to go, or something.
I started a new release section that we can fill in the details of later.

Release notes 2019-04-25+

---

pages/k8s/release-notes.md

fix typo in release notes

---

pages/k8s/cni-calico.md
pages/k8s/cni-canal.md
pages/k8s/cni-flannel.md

Adjust tables to work on ubuntu.com flavour markdown

---

pages/k8s/release-notes.md

Is it too late to add a known issue for the CDK 1.15 release?

Add known issue for containerd+LXD

---

pages/k8s/using-vault.md

Depends on: https://github.com/charmed-kubernetes/layer-etcd/pull/158
Depends on: https://github.com/charmed-kubernetes/charm-kubeapi-load-balancer/pull/2
Depends on: https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/34
Depends on: https://github.com/charmed-kubernetes/charm-kubernetes-worker/pull/22

Add documentation on transitioning CDK from EasyRSA to Vault

---

index.md
pages/k8s/cni-calico.md
pages/k8s/metallb.md
pages/k8s/overview.md
pages/k8s/storage.md
pages/k8s/using-vault.md

Fixes #222
Fixes #188 
Fixes #200

Miscellaneous fixes for 1.15

---

index.md
pages/k8s/cni-calico.md
pages/k8s/metallb.md
pages/k8s/overview.md
pages/k8s/storage.md
pages/k8s/using-vault.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/223

Backport #223 to current

---

_data/sidebars/k8smain-sidebar.yml

As it's already linked from Upgrading doc

Expose the Backups doc in the sidebar

---

_data/sidebars/k8smain-sidebar.yml

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/231

Backport #231 to current

---

assets/calico-overlay.yaml
assets/canal-overlay.yaml
assets/tigera-overlay.yaml

Created overlay files for deployment with specific CNI options.

Cni overlays

---

pages/k8s/get-in-touch.md

Add source link

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

Those with new features going into 1.16, please start getting those features and their short descriptions added here.

WIP: placeholder for 1.16 release notes

---

pages/k8s/operations.md

Wording seems awkward, but I have faith in evilnick.

Updating dashboard URL for 1.16 or greater k8s versions.

---

assets/kata-aws-overlay.yaml
pages/k8s/kata.md

Adding AWS Kata Containers example

---

pages/k8s/upgrade-notes.md

Docs for https://bugs.launchpad.net/charm-etcd/+bug/1843497

Add upgrade note for 1.15 etcd data loss

---

pages/k8s/operations.md

Add clarification for juju scp

---

pages/k8s/validation.md

Update upstream link

---

pages/k8s/docker-registry.md

remove kubernetes-worker/docker-registry relation

---

pages/k8s/logging.md

Revert to HTML for styling code in graylog

---

pages/k8s/monitoring.md

Not sure if this should live here or if we should have a different section for Juju k8s charms. I'm putting this here so we have the copy and we can move it where we need later if it needs to move.
Should go live with https://github.com/charmed-kubernetes/charm-kube-state-metrics/pull/1.

Adding kube-state-metrics docs.

---

pages/k8s/monitoring.md

Reverts charmed-kubernetes/kubernetes-docs#312

Revert "Adding kube-state-metrics docs."

---

pages/k8s/monitoring.md

Docs to show how to operate with kube-state-metrics.

Adding kube-state-metrics docs

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

Feature owners, please add appropriate release notes and fill-in any known issues.
This should remain in `draft` mode until 1.17 date/revisions are added.

1.17 release notes

---

pages/k8s/ldap.md

Add quotes around yaml config value

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/supported-versions.md

Adds basic info from old wiki page, updated for current version

Add versions page

---

pages/k8s/hacluster.md

Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/344

Fix HAcluster page using incorrect ha-cluster-vips option and weird quotes

---

pages/k8s/aws-iam-auth.md
pages/k8s/operations.md
pages/k8s/using-vault.md

Fixes #348 and various other links

various 404 fixes

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

1.17ck2 release notes

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

fix revision for bundle

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/cni-multus.md
pages/k8s/cni-overview.md
pages/k8s/multiple-networks.md

First draft of Multus documentation.

Add Multus documentation

---

pages/k8s/upgrading.md

Various fixes to the Upgrades page
Fixes #380 
Fixes #381 
Fixes #382

Upgrade upgrades page

---

pages/k8s/docker-registry.md

Brief attempt to get this in the docs.  We probably don't need to add any more though.

Document the relation between docker-registry and container runtime

---

pages/k8s/charm-openstack-integrator.md

Part of https://bugs.launchpad.net/charm-openstack-integrator/+bug/1848015

Fix K8s storage example in README

---

pages/k8s/install-local.md

Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/390

Add special kube-proxy config to local install page

---

pages/k8s/docker-registry.md

We pulled in some duplicate content with #388.  Refactor the container-runtime relation bits to remove dupes and flow better.

refactor container-runtime relation bits

---

pages/k8s/keepalived.md

Remove redundant setting of port for keepalived

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

WIP until 1.18+ck1 is released.  Replace `xxx` with appropriate release date and charm store revisions.

add 1.18+ck1 boilerplate plus containerd notes

---

pages/k8s/container-runtime.md

Add extra info to container runtime page

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/snaps.md

reference page for snaps, moved from Wiki

Add snaps info page

---

pages/k8s/auth.md

- separate auth page into authz and authn sections
- call out new defaults and config changes in 1.19
- add section for managing users with k8s-master actions
- remove section on basic_auth.csv
- add section for integrating with external authn services

auth updates

---

pages/k8s/cis-compliance.md

Adds a new heading to describe the changes made in 1.19 to be cis-compliant.

document 1.19 changes needed for compliance

---

pages/k8s/supported-versions.md

Adds the table of bundle versions to fix #456

Add table to supported versions page

---

pages/k8s/1.16/upgrading.md
pages/k8s/1.17/upgrading.md
pages/k8s/1.18/upgrading.md
pages/k8s/1.19/upgrading.md
pages/k8s/upgrading.md

Add links to general upgrade page
Add specific titles to versioned upgrades
Add CDK Addons note to 1.18

Upgrade upgrade pages

---

pages/k8s/1.19/release-notes.md

- Add MetalLB Operator info
- Add link to upstream docs
- Add link to charm github
Do we need to add a link to the charmstore once the charm will be published?

Add MetalLB info in the release notes

---

pages/k8s/monitoring.md

Tested with CK stable and edge.

Pinning monitoring stack charm revisions

---

pages/k8s/metallb.md

Moving over some additional detail from the repo README.
See also: https://github.com/charmed-kubernetes/metallb-operator/pull/6

Improve MetalLB docs

---

pages/k8s/1.19/components.md
pages/k8s/1.19/release-notes.md
pages/k8s/install-manual.md
pages/k8s/release-notes.md
pages/k8s/supported-versions.md

This just syncs back the fixes we applied direct to ubuntu.com for speed.

sync changes made to ubuntu.com

---

pages/k8s/custom-loadbalancer.md
pages/k8s/high-availability.md

Add notes on native loadbalancers

---

pages/k8s/upgrading.md

I hope this makes it a bit clearer. This cost me a couple of minutes during my own upgrade.

Streamline etcd snapshot download

---

pages/k8s/charm-openstack-integrator.md

Ported from https://github.com/juju-solutions/charm-openstack-integrator/pull/26

Fix ambiguous relations in OpenStack Integrator doc

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/packages.md

- Renames snaps to packages
- Adds support for installing via PPA
Signed-off-by: Adam Stokes <51892+adam-stokes@users.noreply.github.com>

Add debian packages to page

---

pages/k8s/1.19/release-notes.md

Needs:
-  release notes
-  update charm revs
- update links for charm bundle

WIP: update for 1.19ck1

---

pages/k8s/docker-registry.md

Update private registry doc to indicate all images required

---

pages/k8s/upgrading.md

Updates version numbers used in upgrade page

Update upgrade template

---

pages/k8s/cni-calico.md

Update Calico docs for VXLAN

---

pages/k8s/cdk-addons.md

Documentation of how to deploy k8s dashboard operator.
Signed-off-by: Dominik Fleischmann <dominik.fleischmann@canonical.com>

Add info about K8s Dashboard operator charm

---

pages/k8s/cdk-addons.md

until such a point as we have docs in the charm

Link to store page for coredns charm

---

pages/k8s/install-local.md

Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/526
I don't think we should recommend this any more.

Remove proxy-mode=userspace from LXD docs

---

pages/k8s/1.18/upgrading.md
pages/k8s/1.19/upgrading.md
pages/k8s/1.20/upgrading.md
pages/k8s/upgrade-notes.md
pages/k8s/upgrading.md

Fixes https://bugs.launchpad.net/charm-etcd/+bug/1913227

Warn users about etcd 3.2 and instruct them how to upgrade to 3.4

---

pages/k8s/quickstart.md
pages/k8s/troubleshooting.md
pages/k8s/upgrade-notes.md
pages/k8s/upgrading.md

just a housekeeping commit of changes made in the published docs

Backports from published docs

---

pages/k8s/upgrading.md

Add a warning to the generic upgrade page (to be propagated to versioned upgrade docs)
Would it be useful to add a list of specific things here?
Fixes #496

Add warning re upgrades

---

pages/k8s/charm-etcd.md

Documentation change related to https://github.com/charmed-kubernetes/layer-etcd/pull/183

Etcd restore supported on cluster deployments

---

pages/k8s/using-vault.md

Fix a link to vault charm post-deployment tasks.

Update using-vault.md - fix a link

---

pages/k8s/install-local.md

Add info about LXD bug

---

pages/k8s/1.21/release-notes.md
pages/k8s/install-manual.md
pages/k8s/release-notes.md
pages/k8s/supported-versions.md

Not really anything to note for this release, just a couple bug fixes.
I'll get you the bundle rev and date soon.

Release notes for 1.21+ck1

---

pages/k8s/1.21/release-notes.md
pages/k8s/install-manual.md
pages/k8s/release-notes.md
pages/k8s/supported-versions.md

Added revs and dates for the 1.21+ck2 release.  The promotion job is running now, so i'll hold this in draft until all these make it to stable.

rel notes for 1.21+ck2

---

pages/k8s/1.16/charm-flannel.md
pages/k8s/1.16/charm-keepalived.md
pages/k8s/1.17/charm-flannel.md
pages/k8s/1.17/charm-keepalived.md
pages/k8s/1.18/charm-flannel.md
pages/k8s/1.18/charm-keepalived.md
pages/k8s/1.19/charm-flannel.md
pages/k8s/1.19/charm-keepalived.md
pages/k8s/1.20/charm-flannel.md
pages/k8s/1.20/charm-keepalived.md
pages/k8s/1.21/charm-flannel.md
pages/k8s/1.21/charm-keepalived.md
pages/k8s/charm-easyrsa.md
pages/k8s/charm-flannel.md
pages/k8s/charm-keepalived.md

update various references to deploying charms so they work with recent Juju/charmstore

Charm updates

---

pages/k8s/1.16/charm-flannel.md
pages/k8s/1.16/charm-keepalived.md
pages/k8s/1.17/charm-flannel.md
pages/k8s/1.17/charm-keepalived.md
pages/k8s/1.18/charm-easyrsa.md
pages/k8s/1.18/charm-flannel.md
pages/k8s/1.18/charm-keepalived.md
pages/k8s/1.19/charm-easyrsa.md
pages/k8s/1.19/charm-flannel.md
pages/k8s/1.19/charm-keepalived.md
pages/k8s/1.20/charm-easyrsa.md
pages/k8s/1.20/charm-flannel.md
pages/k8s/1.20/charm-keepalived.md
pages/k8s/1.21/charm-easyrsa.md
pages/k8s/1.21/charm-flannel.md
pages/k8s/1.21/charm-keepalived.md
pages/k8s/charm-easyrsa.md
pages/k8s/charm-flannel.md
pages/k8s/charm-keepalived.md

Charm updates 2

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/proxy-settings.md

add proxy page

---

pages/k8s/1.21/release-notes.md
pages/k8s/install-manual.md
pages/k8s/release-notes.md
pages/k8s/supported-versions.md

Hey @evilnick, sorry I'm a bit late getting this to you. I just released 1.21+ck3 to stable, so the dates and bundle revs here are final. This should be ready to go.

1.21+ck3 release notes and rev updates

---

pages/k8s/cni-calico.md

This feature will go out with 1.22.

Add service IP advertisement to Calico CNI page

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/equinix.md

This adds a page specifically for deploying on Equinix

 Add equinix page

---

pages/k8s/equinix.md

Various style fixes and clarifications

Equinix fixes

---

pages/k8s/equinix.md

temporarily remove non-working overlay in favour of a temporary custom bundle

Extra equinix stuff

---

pages/k8s/proxies.md

Fixed the broken link to edit this proxies page

Update the edit this page link for proxies.md

---

pages/k8s/1.23/charm-azure-integrator.md
pages/k8s/1.23/charm-calico.md
pages/k8s/1.23/charm-containerd.md
pages/k8s/1.23/charm-docker.md
pages/k8s/1.23/charm-kubernetes-master.md
pages/k8s/1.23/charm-kubernetes-worker.md
pages/k8s/1.23/charm-openstack-integrator.md
pages/k8s/1.23/charm-tigera-secure-ee.md
pages/k8s/charm-azure-integrator.md
pages/k8s/charm-calico.md
pages/k8s/charm-containerd.md
pages/k8s/charm-docker.md
pages/k8s/charm-kubernetes-master.md
pages/k8s/charm-kubernetes-worker.md
pages/k8s/charm-openstack-integrator.md
pages/k8s/charm-tigera-secure-ee.md

fix table spaces in charm pages

---

pages/k8s/monitoring.md

added note about making sure the charms are the same series

+ note making sure the charms are the same series

---

pages/k8s/install-local.md

We found this issue during the installation in a single machine.
Thanks to @maxgio92 for his support :)

docs(install-local): Adding troubleshooting

---

pages/k8s/install-manual.md
pages/k8s/supported-versions.md

The charm store auto-magic is not working and returns the wrong version. Needed updating anyhow

Fix versioned install example

---

pages/k8s/cdk-addons.md

Depends upon charm built from
* https://github.com/charmed-kubernetes/kubernetes-metrics-server-operator/pull/2

update metrics-server addons description

---

pages/k8s/cdk-addons.md
pages/k8s/tigera-secure-ee.md

This one's for you, @evilnick :)
- use a tigera overlay with CK
- use the k8s-dashboard operator charm

use overlays and charms instead of bespoke bundles

---

pages/k8s/openstack-integration.md

Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/687
Related PR for the bundle repo: https://github.com/charmed-kubernetes/bundle/pull/842

Remove kube-api-endpoint relation from OpenStack overlay

---

pages/k8s/1.22/upgrading.md
pages/k8s/1.23/upgrading.md

some style format and text/link fixes already fixed on u.c

upgrade page formatting

---

pages/k8s/1.24/upgrading.md

Fix docker2containerd link

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/cdk-addons.md
pages/k8s/how-to-addons.md

This is still a WIP as I need to do all the steps for the Howto page

Addons update

---

pages/k8s/1.18/upgrading.md
pages/k8s/1.19/upgrading.md
pages/k8s/1.20/upgrading.md
pages/k8s/1.21/upgrading.md
pages/k8s/1.22/upgrading.md
pages/k8s/1.23/upgrading.md
pages/k8s/1.24/upgrading.md
pages/k8s/upgrading.md

Add juju controller upgrade link

---

pages/k8s/metallb.md

use the `containers-metallb` bundle and resolve some page formatting issues

update metallb deployment instructions

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/charm-reference.md
pages/k8s/cni-kube-ovn.md
pages/k8s/cni-overview.md
pages/k8s/install-manual.md

I'm still working on this, but here is my progress so far.

Add Kube-OVN documentation

---

pages/k8s/gatekeeper.md

Add gatekeeper docs

---

pages/k8s/monitoring.md

anyone verify these are the correct relations?

Apparently this monitoring overlay is out of date

---

pages/k8s/get-in-touch.md

Out with the old, in with the new.

update our get-in-touch page with current locations

---

pages/k8s/keepalived.md

For a rationale behind these changes, see https://github.com/charmed-kubernetes/charm-kubernetes-control-plane/pull/250#issuecomment-1282931463

Update keepalived relations and configuration

---

pages/k8s/1.24/upgrading.md
pages/k8s/cni-calico.md
pages/k8s/release-notes.md
pages/k8s/tigera-secure-ee.md

Tried to fix each 404'ing link across the projects from the [results of the latest linkchecker](https://github.com/canonical/ubuntu.com/actions/runs/4204020714/jobs/7294138262) run.
I had to make some judgement calls as the Calico docs have changed quite a bit. So please let me know if anything is inaccurate.

Fix some erroneous links across the project

---

pages/k8s/audit-logging.md
pages/k8s/logging.md

Update the deployment examples.  Call out audit logging and where to find more info.  Fix upstream links.

update logging docs to align with ncsc

---

pages/k8s/1.16/charm-kubernetes-master.md
pages/k8s/1.17/charm-kubernetes-master.md
pages/k8s/1.18/charm-kubernetes-master.md
pages/k8s/1.19/charm-kubernetes-master.md
pages/k8s/1.20/charm-kubernetes-master.md
pages/k8s/1.21/charm-kubernetes-master.md
pages/k8s/1.22/charm-kubernetes-master.md
pages/k8s/1.23/charm-kubernetes-master.md
pages/k8s/logging.md
pages/k8s/operations.md
pages/k8s/release-notes.md

Link fixes 2303

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/kubevirt.md

* Adding a kubevirt charm page
* Adding a new sidenave options to navigate to this page

Addition of kubevirt documentation

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/1.23/upgrading.md
pages/k8s/1.24/upgrading.md
pages/k8s/1.25/upgrading.md
pages/k8s/1.26/upgrading.md
pages/k8s/1.27/upgrading.md
pages/k8s/backups.md

* etcd updates
* fix local nav
* remove \n
* update updates for 1.23 and 1.24 also
* clarification on etcd version

etcd updates (#774)

---

pages/k8s/packages.md

- removes reference to deb package installs
- some minor word tweaks

Remove mentions of deb packages

---

pages/k8s/cni-cilium.md

This pull request adds a note to alert users if deploying CK + Cilium on clouds like AWS and OpenStack.

Add Note for CK + Cilium on AWS/Openstack

---

pages/k8s/1.28/release-notes.md
pages/k8s/release-notes.md

Including the new Bug fixes since 1.28 release

Adding release notes based on comments from Launchpad issues for 1.28+ck1

---

pages/k8s/high-availability.md

woke-checker isn't so good at images

update ha page and images

---

pages/k8s/explain-cloud.md

* First draft of explain-cloud page, as to why someone needs cloud provider charms
* edits on explain-cloud.md
---------

Add docs regarding WHY someone needs cloud-provider charms (#805)

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/explain-backups.md
pages/k8s/shared/_side-navigation.md

This adds a page explaining backups, with links to other docs and the etcd Howto page

Add page for backups

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/explain-backups.md
pages/k8s/shared/_side-navigation.md

* Add page for backups
* Update pages/k8s/explain-backups.md
---------

Add page for backups (#812)

---

pages/k8s/1.29/release-notes.md
pages/k8s/1.29/upgrading.md
pages/k8s/how-to-cos-lite.md
pages/k8s/upgrade-notes.md

some tweaks and fixes that keep us in sync with u.c

sync with u.c

---

pages/k8s/openstack-integration.md

It seems to be ":lb-consumers" instead of ":lb-consumer".

Update openstack-integration.md: Misspelling "lb-consumers" instead of "lb-consumer"

---

pages/k8s/1.31/release-notes.md
pages/k8s/release-notes.md

Thanks to the @perk for having sharp eagle eyes 🦅 and noticing the need to correct the Component Versions

Correct default component versions

---

pages/k8s/install-existing.md

Fix typo in "Installing Charmed Kubernetes on Existing Machines"

---

index.md

now canonical k8s webpage is correct, remove this link at the top of charmed k8s

Revert changes to home page

---

pages/k8s/security.md

Fix broken link in the security page

---

pages/k8s/upgrading.md

This page was overlooked in previous releases

Update upgrading pages with relavent versions

---

generator/k8s_docs_tools/templates/upgrading.j2
pages/k8s/1.30/upgrading.md
pages/k8s/1.31/upgrading.md
pages/k8s/1.32/upgrading.md
pages/k8s/ceph.md
pages/k8s/certs-and-trust.md
pages/k8s/cni-cilium.md
pages/k8s/encryption-at-rest.md
pages/k8s/equinix.md
pages/k8s/gatekeeper.md
pages/k8s/how-to-cos-lite.md
pages/k8s/install-existing.md
pages/k8s/install-local.md
pages/k8s/install-manual.md
pages/k8s/install-offline.md
pages/k8s/keepalived.md
pages/k8s/logging.md
pages/k8s/metallb.md
pages/k8s/multiple-networks.md
pages/k8s/proxies.md
pages/k8s/quickstart.md
pages/k8s/scaling.md
pages/k8s/security.md
pages/k8s/storage.md
pages/k8s/upgrading.md
pages/k8s/using-vault.md
pages/k8s/vsphere-integration.md

Juju went through a major rework and most of the links don't have redirects so this is updating those links for visible pages

docs: update juju docs after rework

---

pages/k8s/1.31/release-notes.md
pages/k8s/1.32/release-notes.md
pages/k8s/release-notes.md

Add release notes for `1.32+ck2` and `1.31+ck3`.

Prepare Bugfix Release Notes for `1.32+ck2` and `1.31+ck3`

---

pages/k8s/validation.md

Drop unnecessary relation in kubernetes validation

Drop unnecesary relation in kubernetes-e2e
