_data/sidebars/k8smain-sidebar.yml
pages/k8s/logging.md

This replicates and improves on the current logging page from upstream, including more relevant examples and excluding at least one significant error

Add logging page

---

_includes/vanilla-overrides.html
_layouts/base_noedit.html
index.md

The links will appear on content pages, linking directly to the content on github

Add "Edit this page" link and template

---

pages/release-notes/20180817-1.12

Requested by IS here: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/676#issuecomment-431267884
I think it makes sense - we've updated our recommendations on how to configure proxy settings for CDK, and the release notes are a good vehicle for informing users of that change.

Add proxy config to 1.12 release notes

---

pages/k8s/release-notes.md

Sorry, I remembered the u.c site is not currently set to process individual files, so I have merged the release notes onto the main release-notes page

Move release notes, add docs links

---

pages/k8s/docker-registry.md

The default deploy is secure with an easyrsa relation. Tweak the security section to note this can be done via config.

docker registry: tweak security section

---

pages/k8s/audit-logging.md

@evilnick I have no idea if this is of any significance or if this PR is correct, but I noticed that the audit-logging page references an `operations` tag, whereas most of the other pages reference `operating` instead.

Change audit logging page tag to match other pages

---

pages/k8s/release-notes.md
pages/k8s/upgrade-notes.md

There's an [issue with CoreDNS 1.3.1](https://github.com/coredns/coredns/issues/2629) and we've [specifically chosen to use CoreDNS 1.4.0 instead](https://github.com/juju-solutions/cdk-addons/pull/84). It's probably good to call out in the release notes which version of CoreDNS we're shipping, for users who might be wondering about it.
I went ahead and put it in the upgrade notes too.

Add CoreDNS version to release notes and upgrade notes

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/install-manual.md
pages/k8s/operations.md

@tvansteenburgh This basically fixes #110 IMO, and draws together the manual, quickstart and potentially any other install pages we add (they can all point here).
There are parts which can be improved for sure, but I think it would be good to get this in with the 1.14 stuff (and helps with the "try this version" story).

Add basic operations page

---

pages/k8s/install-manual.md

1.13 bundle revision number is updated because we did an interim stable release between 1.13 and 1.14.

Add 1.14 bundle reference

---

pages/k8s/install-manual.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/137

Backport #137 to current

---

pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/141

Backport #141 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/juju-solutions/kubernetes-docs/pull/145

Backport #145 to current

---

pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/153

Backport #153 to current

---

pages/k8s/aws-integration.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/160

Backport #160 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/163

Backport #163 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/169

Backport #169 to current

---

pages/k8s/install-manual.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/171

Backport #171 to current

---

assets/openstack-overlay.yaml
pages/k8s/aws-integration.md
pages/k8s/gcp-integration.md
pages/k8s/openstack-integration.md

Add documentation page for OpenStack integrator

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/184

Backport #184 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/192

Backport #192 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/201

Backport #201 to current

---

pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/212

Backport #212 to current

---

pages/k8s/cni-calico.md
pages/k8s/cni-canal.md
pages/k8s/cni-flannel.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/214

Backport #214 to current

---

pages/k8s/container-runtime.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/216

Backport #216 to current

---

pages/k8s/using-vault.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/219

Backport #219 to current

---

pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/218

Backport #218 to current

---

pages/k8s/backups.md

Otherwise the subsequent restore action will fail with:
FileNotFoundError: [Errno 2] No such file or directory:
'/var/snap/etcd/common/etcd.conf.yml'
Because "new-etcd" is not bootstrapped yet since no CA is available.
Naming easyrsa as "new-easyrsa" is necessary since new-etcd will be
stuck if an existing easyrsa is used. The issue is tracked as
LP: #1835056 (https://launchpad.net/bugs/1835056)

Deploy easyrsa as a prerequisite for restore

---

pages/k8s/backups.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/230

Backport #230 to current

---

pages/k8s/backups.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/228

Backport #228 to current

---

pages/k8s/backups.md

As described in LP: #1826009 (https://launchpad.net/bugs/1826009), the
default channel in etcd charm is 2.3/stable. However, Kubernetes bundle
uses 3.2/stable as of today instead so manually specifying the channel
is important to have the same version of etcd as the previous cluster.

Specifying etcd channel is necessary

---

pages/k8s/backups.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/235

Backport #235 to current

---

pages/k8s/upgrade-notes.md

In this section.
https://github.com/charmed-kubernetes/kubernetes-docs/blob/a5a3e3df4d092b747841cdc55e617505f6771aca/pages/k8s/upgrade-notes.md#to-keep-docker-as-the-container-runtime

Add a missed link for [Docker configuration page][docker-page]

---

pages/k8s/using-vault.md

During testing of the EasyRSA->Vault transition, we found two things:
1. It goes more smoothly if you migrate etcd first, then kubernetes second.
2. Users may need to restart certain workloads they have deployed, if those workloads use ServiceAccounts to talk to the Kubernetes API.
This PR updates the documentation to account for the above two points.

Revise doc for EasyRSA->Vault transition

---

pages/k8s/using-vault.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/241

Backport #241 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

@tvansteenburgh noticed that the revision of charmed-kubernetes in stable does not match the docs. Here's a quick fix.
Based on IRC logs:
1. We didn't release CK 1.15 to stable until June 28th.
2. Within a few hours of releasing charmed-kubernetes-139, we released charmed-kubernetes-142 which fixed a minor problem where bundle revisions didn't 100% match charm revisions in stable.

Fix CK 1.15 bundle rev and date

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/251

Backport #251 to current

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The original PR this was ported from can be viewed here:https://github.com/charmed-kubernetes/kubernetes-docs/pull/253

Backport #253 to current

---

pages/k8s/auth.md
pages/k8s/aws-iam-auth.md
pages/k8s/aws-integration.md

Just wanted to get this up here so you can start changing my z's to s's.

aws-iam documentation

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/kata.md
pages/k8s/untrusted-container-runtime.md

Need to add this to the sidebar, but I can find `"shared/_side-navigation.md"`.

Add Kata Containers docs

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/snap-refresh.md

Ahoy @evilnick!  Not sure if this warrants a new page, but here is a _page-like object_ for you to consume as you see fit.  It's meant to give users more detail about the `snapd_refresh` config option available on `etcd`, `k8s-master`, and `k8s-worker` charms.

page about snapd_refresh

---

pages/k8s/aws-iam-auth.md

* Clarified what nodes needed to be able to reach out to AWS.
* Added a section about setting up the AWS role and linked to upstream docs.
* Added a note to be sure to have a CRD set before enabling the aws context.
* Added clarification about the environment variables read by the `aws-iam-authenticator` binary.

Updating docs per peer review. Thanks @tvansteenburgh.

---

pages/k8s/release-notes.md

Tim suggested that we point out that the Kubernetes dashboard is moving from stable to a beta out of necessity, but this isn't called out anywhere. He suggested an addition in the release notes to point out that it is known to be a beta product and users should expect beta behavior.

Adding comment about Kubernetes dashboard

---

pages/k8s/using-vault.md

From testing, the manual non-HA-to-HA transition steps are not necessary, so this cleans them up in favor of an overlay.
Depends on: https://github.com/charmed-kubernetes/bundle/pull/755

Clean up instructions for Vault HA

---

assets/graylog-vhost.tmpl
pages/k8s/logging.md
pages/k8s/monitoring.md

This is a redo of #199. Now that the graylog charm officially supports v3, we can get rid of the hacky deployment/config steps and document graylog deployment with an overlay.
Depends on https://github.com/charmed-kubernetes/bundle/pull/757

add graylog logging section

---

pages/k8s/snap-coherence.md

Describe the setup and usage of a snap store proxy in our docs.  This lets admins control which snap revisions are installed by using a proxy.
@evilnick, the concept of "control over snaps" is also covered in the following page:
https://ubuntu.com/kubernetes/docs/snap-refresh
While `snap-refresh` doesn't let admins lock to a specific revision, it does allow them to pause snap refreshes indefinitely.  I think we should have some verbiage somewhere that says "we recommend using `snap-coherence` with 1.17 and above; controlling snaps with `snap-refresh` is deprecated".

new page about snap coherence

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

Bugs fixed:
https://launchpad.net/charmed-kubernetes/+milestone/1.16+ck2
WIP until code merges are in stable -- just in case we need to call out more than a bug link.

add 1.16-ck2 release notes

---

pages/k8s/benchmarking.md

This PR adds a new **Benchmarking** page to the k8s docs to describe the new `kube-bench` functionality that will debut in 1.17:
https://bugs.launchpad.net/charm-kubernetes-master/+bug/1841262

add benchmarking page

---

pages/k8s/install-manual.md
pages/k8s/release-notes.md

The release is currently in candidate and has not been released to stable yet, so the release date and bundle revision are tentative.
Since this release only includes a fix for a single issue, I changed the usual text:
> A list of bug fixes and other minor feature updates in this release can be found at (link)
and wrote something more specific to the issue instead.

Release notes for 1.17+ck1

---

pages/k8s/aws-integration.md
pages/k8s/gcp-integration.md
pages/k8s/openstack-integration.md

Trying to 'juju deploy charmed-kubernetes  --overlay ~/aws-overlay.yaml' fails with:
ERROR Bundle cannot be deployed without trusting applications with your cloud credentials.
Please repeat the deploy command with the --trust argument if you consent to trust the following application(s):
- aws-integrator

Replaced trust step with --trust parameter

---

pages/k8s/ldap.md

Include config change to turn on RBAC auth mode.
Necessary because the default is "AlwaysAllow".

Include config change to turn on RBAC auth mode

---

pages/k8s/ldap.md

The default policy is already there by the default charm config.
https://jaas.ai/u/containers/kubernetes-master#charm-config-keystone-policy
Mark the step of loading a custom policy as optional.

Mark loading keystone policy as optional

---

pages/k8s/storage.md

This adds a bit more info regarding CephFS, calling out the storage class that is automatically added.  It also updates the example output to make it more accurate.

Add more info to CephFS doc

---

pages/k8s/openstack-integration.md

Adjust the cinder example to match the storage class that gets created by default.

tweak examples to match default storage class

---

pages/k8s/openstack-integration.md

The kube-api-endpoint relation was originally being proxied between k8s-master and k8s-worker via kubeapi-load-balancer, but with that being removed, needs to be directly established between the master and worker.
This mirrors the fix in charmed-kubernetes/bundle#768

Add missing kube-api-endpoint relation in OpenStack LB overlay

---

pages/k8s/backups.md

The steps currently described to restore an etcd snapshot deploy
a new easyrsa application, but those steps miss relating it to
kubernetes-worker, kubernetes-master and kubeapi-load-balancer
applications. This patch includes those relations in the
documentation.
Fixes #372

Add missing relations on snapshot restore

---

pages/k8s/storage.md

This documents the workaround for the CephFS RWX volume mount permissions issue that we are stuck with for the time between [LP #1868150](https://bugs.launchpad.net/cdk-addons/+bug/1868150) and [LP #1867940](https://bugs.launchpad.net/cdk-addons/+bug/1867940). This partially mitigates [LP #1866262](https://bugs.launchpad.net/cdk-addons/+bug/1866262) by documenting the interim workaround.

Document initContainers workaround for CephFS RWX perm issue

---

pages/k8s/release-notes.md

Hopefully this will merge neatly into @kwmonroe's branch.  Adding the release notes from https://bugs.launchpad.net/charm-containerd/+bug/1866040

Adding containerd version hold to release notes

---

pages/k8s/cis-compliance.md

The action syntax has changed in 1.18 due to our new support of the CIS Kubernetes Benchmark v1.5.0.
Adjust our reference page accordingly.

update cis action syntax and default changes for 1.18

---

pages/k8s/1.16/charm-keepalived.md
pages/k8s/1.17/charm-keepalived.md
pages/k8s/1.18/charm-keepalived.md
pages/k8s/charm-keepalived.md
pages/k8s/keepalived.md

This clarifies the clouds on which keepalived is expected to work due to the VIP routing and VRPP protocol requirements.
This was split off of #402 and backports to previous release docs added to make review and merging easier.

Add some additional info to keepalived docs

---

pages/k8s/1.16/charm-etcd.md
pages/k8s/1.17/charm-etcd.md
pages/k8s/1.18/charm-etcd.md
pages/k8s/charm-etcd.md
pages/k8s/docker-registry.md

Because some shells (inc. zsh) will try to expand it.

Preface cs: to charm URL

---

pages/k8s/cni-multus.md
pages/k8s/release-notes.md

Now that Juju 2.8.0 has been released to stable, we can clean up the Multus instructions a bit.

Update Multus docs for Juju 2.8.0 stable

---

pages/k8s/charm-aws-integrator.md

Adds documentation for the AWS RDS integration.
Part of [lp:1883963](https://bugs.launchpad.net/charm-aws-integrator/+bug/1883963)

Add documentation for AWS RDS

---

pages/k8s/auth.md

This space is not cleaned up by charms and causes the API server to fail.

Remove space in authorization-mode

---

_data/sidebars/k8smain-sidebar.yml

Splits out the three security related pages from the somewhat overloaded Operations section of the navigation.

Create Security section in navigation

---

pages/k8s/install-local.md

I ran into an issue recently when upgrading a k8s-worker charm to a local revision.  `kube-proxy` wouldn't start.
I had to re-apply the profile and remove/add the unit to get things working.  I figured it may be a useful troubleshooting technique.

add a troubleshooting blurb about lxd-profile

---

pages/k8s/storage.md

CephFS support requires OpenStack Train, but according to https://wiki.ubuntu.com/OpenStack/CloudArchive Xenial only goes up to Queens.
Drive-by: Document the need to set the `install_sources` config, and fix the formatting of the `initContainer` example by breaking it out from the note call-out.
Part of [lp:1879542](https://bugs.launchpad.net/charmed-kubernetes-testing/+bug/1879542)

Update CephFS notes to exclude Xenial

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/ipv6.md

Part of [lp:1881177](https://bugs.launchpad.net/charm-etcd/+bug/1881177)
Depends on:
* https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/99
* https://github.com/charmed-kubernetes/charm-kubernetes-worker/pull/63
* https://github.com/charmed-kubernetes/layer-kubernetes-common/pull/13
* https://github.com/charmed-kubernetes/layer-calico/pull/58

Add page for IPv6 networking in cluster

---

pages/k8s/1.19/upgrading.md

With the authentication changes in 1.19, we should callout a few notes specific to upgrading to >= 1.19.

callout authn upgrade notes

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/cni-multus.md
pages/k8s/cni-overview.md
pages/k8s/cni-sriov.md

This primarily adds a doc page for SR-IOV.
I also updated the CNI overview page a bit to make the distinction between "base CNI" (flannel, calico, canal, tigera-secure-ee) vs. "CNI addon" (multus, sriov) a bit clearer.

Add SR-IOV doc page

---

pages/k8s/aws-iam-auth.md

With 1.19's CIS benchmark work, we've disabled the insecure addr/port options to the apiserver. This means users will need to explicitly set a `--kubeconfig <file>` when calling `juju run x -- kubectl y`.
A quick grep through the docs only showed 1 required change in the aws-iam page.

need to include --kubeconfig in 1.19+

---

assets/keystone.yaml
pages/k8s/1.19/release-notes.md
pages/k8s/auth.md

- Unpin the charms in the keystone.yaml asset; this matches our other
deployment assets and 1.19 is known to work with the current stable
charm revisions.
- Add a known issue that port 5000 is expected to be available on all
k8s-master units.
- Describe more about how the authenticator works in the auth page.

1.19 tweaks for authn and keystone

---

pages/k8s/install-manual.md

Configuration change example contains snippet that sets `https_proxy` option on `kubernetes-worker`, but this option seem to be deprecated and results in error
```
{}
ERROR unknown option "https_proxy"
```
However, the `https_proxy` option can be set on `containerd` app instead.

https_proxy option does not work on kubernetes-worker

---

pages/k8s/metallb.md

This goes with https://github.com/charmed-kubernetes/metallb-operator/pull/1 , the new operator brings a new preferred way to deploy MetalLB in charmed environments.

Update MetalLB docs to add MetalLB Operator info

---

pages/k8s/1.19/release-notes.md
pages/k8s/release-notes.md

Stumbled across this TODO in the release notes. Followed it through to [the PR](https://github.com/charmed-kubernetes/cdk-addons/pull/191/files) where we set it to 1.18.0.

Fix cloud-provider-openstack TODO in 1.19 release notes

---

pages/k8s/1.19/release-notes.md
pages/k8s/release-notes.md

We should be able to remove this note now that https://bugs.launchpad.net/ubuntu/+source/pacemaker/+bug/1881762 is Fix Released.

Remove known issue about Pacemaker from release notes

---

pages/k8s/aws-integration.md

Hi all, 
The kubectl run command examples which are used on the integrator pages are long-since deprecated. 
I've updated the example to include a working command for kubectl create deployment as opposed to kubectl run. 
This was deprecated as of 1.17 if I recall, but is completely broke as of 1.18+. 
Cheers, 
- Calvin

Updated the kubectl run command example as it has been long deprecated

---

pages/k8s/azure-integration.md

Hi all, 
I've updated the azure example for creating a load-balancer with the kubectl create deployment command instead of kubectl run as the command is deprecated and no longer works. 
Cheers,
- Calvin

kubectl run example for exposing the load-balancer is wrong

---

pages/k8s/1.18/charm-aws-integrator.md
pages/k8s/1.18/charm-azure-integrator.md
pages/k8s/1.18/charm-gcp-integrator.md
pages/k8s/1.18/charm-openstack-integrator.md
pages/k8s/1.19/charm-aws-integrator.md
pages/k8s/1.19/charm-azure-integrator.md
pages/k8s/1.19/charm-gcp-integrator.md
pages/k8s/1.19/charm-openstack-integrator.md
pages/k8s/aws-integration.md
pages/k8s/azure-integration.md
pages/k8s/charm-aws-integrator.md
pages/k8s/charm-azure-integrator.md
pages/k8s/charm-gcp-integrator.md
pages/k8s/charm-openstack-integrator.md
pages/k8s/gcp-integration.md
pages/k8s/openstack-integration.md

This only seems of concern in the integrator page examples. This PR fixes the examples in the general pages, the master charm docs and the relevant versioned charm pages.

Update all kubectl run commands (now deprecated)

---

pages/k8s/cdk-addons.md

Documents that CoreDNS can be managed via the new operator charm for more customizability.
Part of [lp:1858007](https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1858007)

Add info about CoreDNS operator charm

---

pages/k8s/ldap.md
pages/k8s/openstack-integration.md

The following patches introduced possibility to obtain Keystone credentials from openstack-integrator.
https://review.opendev.org/c/openstack/charm-interface-keystone-credentials/+/747970
https://github.com/juju-solutions/charm-openstack-integrator/pull/38/files
So I'm describing this option in the documentation.

Add section about using openstack-integrator for keystone-credentials

---

pages/k8s/1.19/upgrading.md

Current command line just gets secrets in the default namespace which does not contain the mentioned secrets
New command line will get them from the kube-system namespace and filter down to just the juju.is/token-auth ones.

Fix command line for secret verification

---

pages/k8s/1.20/upgrading.md
pages/k8s/troubleshooting.md
pages/k8s/upgrade-notes.md
pages/k8s/upgrading.md

This adds:
- a section in the troubleshooting page, detailing the problem and a workaround
- warning at the top of 1.20 upgrade page
-  warning in the upgrade notes

Add warning for LXD

---

pages/k8s/upgrade-notes.md

Follow-up to https://github.com/charmed-kubernetes/kubernetes-docs/pull/527 and today's office hours. Seems like I forgot upgrade notes for informing users about this change. Hopefully this covers it.

Add 1.19 upgrade note to remove proxy-mode=userspace

---

pages/k8s/docker-registry.md

add clarifications for docker registry

---

pages/k8s/azure-integration.md
pages/k8s/charm-azure-integrator.md

The docs portion for the Azure Integrator LB support got missed.
Note: I call out the revision for the k8s-master charm because it's still in edge.
Bundle PR for the overlay: https://github.com/charmed-kubernetes/bundle/pull/803

Add docs for Azure LB support

---

pages/k8s/monitoring.md

Remove defined LMA charm revisions. This change also matches the overlay file referenced.

Don't lock in charm revisions

---

pages/k8s/install-manual.md

Deploying specific version is only possible via charmstore, charmhub only supports channels (AFAIK).
$ juju --version
2.9.12-ubuntu-amd64
$ juju deploy charmed-kubernetes-596
"ERROR specifying a revision for charmed-kubernetes is not supported, please use a channel."
$ juju deploy cs:bundle/charmed-kubernetes-596
Located bundle "charmed-kubernetes" in charm-store, revision 596
[...]
Deploy of bundle completed.

Workaround for deploying specific revision.

---

pages/k8s/release-notes.md

Looks like a few links didn't make it to the main relnotes page from 1.22/relnotes.

fix broken links on main relnotes page

---

pages/k8s/openstack-integration.md

For the OpenStack integration documentation, the role and distinction between the four config options related to load balancer FIP network and tenant subnet info isn't clearly spelled out and was leading to confusion.

Clarify role and usage of subnet and FIP config opts

---

pages/k8s/1.17/release-notes.md
pages/k8s/1.18/release-notes.md
pages/k8s/1.19/release-notes.md
pages/k8s/1.20/release-notes.md
pages/k8s/1.21/release-notes.md
pages/k8s/1.22/release-notes.md
pages/k8s/1.23/release-notes.md
pages/k8s/install-manual.md
pages/k8s/release-notes-historic.md
pages/k8s/release-notes.md
pages/k8s/supported-versions.md

Addresses #643 immediately, while other links still exist to charmstore bundles.

adjust release bundle links to github away from charmstore

---

pages/k8s/gpu-workers.md

p2.xlarge with NVIDIA Tesla K80 GPU is no longer supported by the
default Nvidia driver. Let's bump it to p3.2xlarge with Tesla V100.
> NVRM: The NVIDIA Tesla K80 GPU installed in this system is
> NVRM:  supported through the NVIDIA 470.xx Legacy drivers. Please
> NVRM:  visit http://www.nvidia.com/object/unix.html for more
> NVRM:  information.  The 510.47.03 NVIDIA driver will ignore
> NVRM:  this GPU.  Continuing probe...
> NVRM: No NVIDIA GPU found.
Closes: #646

Refresh AWS GPU enabled instance type

---

pages/k8s/gpu-workers.md

Nowadays, we must specify the image tag explicitly otherwise it fails to
find a image.
https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/README.md#deprecated-latest-tag
Closes: #648

The "latest" image tag is no longer available

---

pages/k8s/1.23/release-notes.md

Looks like the 1.23 release notes were 1/2 merged with 1.22.  Note the odd "What's New" section mid-way down the page that injects 1.22-ck1 and 1.22 bits:
https://ubuntu.com/kubernetes/docs/1.23/release-notes
This PR cleans that up.

fixup 1.23 release notes

---

pages/k8s/gpu-workers.md

Using a command line would be easier than switching to the dashboard all
of a sudden. We should be able to see the identical output in both ways.

Replace the dashboard step with a single command

---

pages/k8s/storage.md

In CK 1.24 we will no longer be supporting the ceph-admin relation (kubernetes-control-plane:ceph-storage <-> ceph-mon:admin). The kubernetes-control-plane charm will get everything it needs from the ceph-client relation instead.
Let me know if there's a different branch I should target this change to.

Remove ceph-admin relation from storage docs

---

pages/k8s/install-manual.md
pages/k8s/ipv6.md

Calico is now the default CNI, so calico-overlay.yaml doesn't really make sense anymore. Let's remove references to it.
Related: https://github.com/charmed-kubernetes/bundle/pull/849

Remove references to calico-overlay.yaml

---

pages/k8s/storage.md

While trying to follow the documentation, I came across these two commands that probably are using an old syntax.

updated command to delete ceph pool

---

pages/k8s/vsphere-integration.md

When I was setting up a test cluster on our Boston vSphere, I needed to run `juju model-config` to set the `datastore` and `primary-network` config variables.
In the case of the Boston cluster, the exact command I used was:
juju model-config datastore=vsanDatastore primary-network=VLAN_2767

Add necessary model configuration command for certain clusters

---

pages/k8s/1.25/release-notes.md
pages/k8s/release-notes.md

* release date currently unset
*  should the [known-issues sections](https://github.com/charmed-kubernetes/kubernetes-docs/blob/6fe5300219a9030b45015cdf3c15b45bc335a2e6/pages/k8s/release-notes.md?plain=1#L184-L195) be updated to remove the warnings

Update release docs to indicate new charms

---

generator/tox.ini
pages/k8s/vsphere-integration.md

Now that the vSphere in-tree provider has been deprecated, we should advise the users to use the new out-of-tree provider (`vsphere-cloud-provider`).

Update vSphere Integration docs

---

pages/k8s/vsphere-integration.md

From the vSphere docs:
- Kubernetes will deprecate the in-tree vSphere volume plug-in, and it will be removed in the future Kubernetes releases. Volumes provisioned using the vSphere in-tree plug-in will not get additional new features supported by the vSphere Container Storage Plug-in.
- Kubernetes provides a seamless procedure to help migrate in-tree vSphere volumes to a vSphere Container Storage Plug-in. After you migrate the in-tree vSphere volumes vSphere Container Storage Plug-in, all subsequent operations on migrated volumes are performed by the vSphere Container Storage Plug-in. The migrated vSphere volume will not get additional capabilities supported by vSphere Container Storage Plug-in.
- Add a section that guides users through the vSphere integration upgrade process to 1.26 …

Add "Upgrading" section to vSphere Integration page

---

pages/k8s/install-manual.md
pages/k8s/vsphere-integration.md

Addresses one part of issue https://github.com/charmed-kubernetes/kubernetes-docs/issues/746 where @ca-scribner wanted to deploy 1.24, but ought to use 1.26/stable charms

Quick Install: overlays operate with latest/stable bundle

---

assets/nvidia-test.yaml
pages/k8s/gpu-workers.md

- adjust flow for a less headache-inducing experience
- add azure instance types (aws and azure are similar; gcp is the odd-cloud out)
- bump `nvidia-test.yaml` image to current supported version for k8s 1.27
- update example syntax and output
- update links
Fixes #593

gpu doc refresh

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/charm-reference.md
pages/k8s/cni-cilium.md
pages/k8s/cni-overview.md
pages/k8s/install-manual.md

This PR adds documentation for installing and using the Cilium CNI plugin in Charmed Kubernetes.

Add Cilium documentation

---

pages/k8s/aws-integration.md
pages/k8s/azure-integration.md
pages/k8s/gcp-integration.md
pages/k8s/vsphere-integration.md

Addresses documentation needs in issue https://github.com/charmed-kubernetes/kubernetes-docs/issues/743 
* AWS Cloud Storage and Cloud Providers
* GCP Cloud Storage and Cloud Providers
* Azure Cloud Storage and Cloud Providers
* VSphere Cloud Storage and Providers in https://github.com/charmed-kubernetes/kubernetes-docs/pull/762

Update AWS Integration page to include cloud-provider and k8s-storage

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/1.23/upgrading.md
pages/k8s/1.24/upgrading.md
pages/k8s/1.25/upgrading.md
pages/k8s/1.26/upgrading.md
pages/k8s/1.27/upgrading.md
pages/k8s/backups.md

- Upgrade pages point to backups page for snapshot and restore of etcd
- backups page adds detail about v2 and v3 data

etcd updates

---

pages/k8s/metallb.md

Quick fix for https://github.com/charmed-kubernetes/kubernetes-docs/issues/784
The MetalLB docs will need to be reworked for CK 1.28, so, these links probably won't be in the docs much longer.

Quick fix MetalLB links for 1.27

---

pages/k8s/1.26/upgrading.md
pages/k8s/1.27/upgrading.md
pages/k8s/1.28/upgrading.md

Improve charm and snap upgrade docs to indicate how to step to a new charm channel.
* switch to using `juju refresh` since it is compatible in juju 2.9
* include `--channel` on charm refresh
* improve configuring the snap channels when configuring k8s-cp and k8s-workers
Fixes #796

Set charm upgrade channels during the upgrade steps

---

pages/k8s/cni-overview.md
pages/k8s/install-local.md

Adjust docs to show how to adjust lxd profiles to expose `/sys/fs/bpf`.  Juju team has accurately warned that exposing more of the host machine's kernel to lxd adjustments will just yield future confusion and it's likely we should adviser users to not deploy CNI's that require these kernel params on LXD.
Doc mitigation for [LP:2034448](https://bugs.launchpad.net/charm-kubernetes-master/+bug/2034448)

Add /sys/fs/bpf note for cnis on lxd which require a profile adjustment

---

pages/k8s/explain-cloud.md

This PR is to address the missing link on the navigation pages for `explain-cloud`.  This should consist of reasons WHY one would need the cloud-provider charms

Add docs regarding WHY someone needs cloud-provider charms

---

pages/k8s/openstack-integration.md

[LP#1940328](https://bugs.launchpad.net/charm-openstack-integrator/+bug/1940328)
Upgrade release documentation to include instructions on migrating from `loadbalancer` relation to the `lb-consumers` relation.
* reference updated overlays https://github.com/charmed-kubernetes/bundle/pull/889
* reference updated [charmhub docs](https://discourse.charmhub.io/t/openstack-integrator-docs-index/12980)

[LP#1940328] openstack-integrator 1.29 release adjustments for installation and upgrade

---

pages/k8s/how-to-install.md
pages/k8s/install-existing.md

Add a section on deploying charmed k8s to a manual juju cloud.

add a manual cloud page to our install instructions

---

_data/sidebars/k8smain-sidebar.yml
pages/k8s/how-to-cos-lite.md
pages/k8s/how-to-operate.md
pages/k8s/shared/_side-navigation.md

This documents how to monitor a charmed k8s deployment using cos-lite deployed on a microk8s substrate in juju.

Add COS Lite integration with Charmed K8s

---

assets/keystone.yaml
pages/k8s/ldap.md
pages/k8s/upgrade-notes.md

⚠️  these notes target the 1.29+ck2 release plans notes
Provide updated documentation on integration with external authn and authz endpoints for charmed-kubernetes.  These changes adjust the `upgrade-notes.md` to explain revision specific upgrade concerns and changes to the `ldap.md` docs  for fresh deployments.  
Upgrades:
I've adjusting the `upgrade-notes.md` which covers ALL versions of charmed-kubernetes but is linked from the `1.29/upgrading.md` page.  Is this enough?  Should these notes be in that page instead?
The upgrade notes provide example situations where the charm may "block" in the event of an upgrade with keystone-credentials enabled and how the user should adjust the charm config in order to continue using the authn and authz endpoints. 
Fresh Install Instructions:
These …

Beginning notes on how to reconfigure for keystone in 1.29

---

pages/k8s/1.29/release-notes.md
pages/k8s/1.30/release-notes.md
pages/k8s/release-notes.md

Creating release notes for 1.29+ck4 and 1.30+ck1
Preparing bug release notes for two simultaneous releases

Update Release Notes for 1.30+ck1

---

pages/k8s/cni-cilium.md

Provides a section in the docs for upgrading cilium through minor revisions

Provide instructions to upgrade cilium versions

---

pages/k8s/1.28/release-notes.md
pages/k8s/1.29/release-notes.md
pages/k8s/1.30/release-notes.md
pages/k8s/1.31/release-notes.md
pages/k8s/release-notes.md

Adding release notes for `CVE-2025-1974` backports

Prepare release notes for 1.28 -> 1.31

---

pages/k8s/cni-cilium.md

This PR updates documents to support recent changes made on cilium charm. These updates include: 
- Supported upstream cilium versions
- Cilium `tunnel-protocol` and `tunnel-port` config options

chore: update cilium cni documents

---

pages/k8s/1.31/release-notes.md
pages/k8s/1.32/release-notes.md
pages/k8s/1.33/release-notes.md
pages/k8s/release-notes.md

Add release notes for `1.33+ck2`, `1.32+ck3`, and `1.31+ck4`.

docs: prepare bugfix release notes for `1.31`, `1.32`, and `1.33`
